name: RunTests
run-name: 🎉 Your First Binary PS Module! 🎉
on: [
  push,
  pull_request
]
defaults:
  run:
    shell: pwsh
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📤 Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 🧪 Pester Tests
        id: test
        run: |
          Write-Host -Fore Green "Running Available Tests in $PWD"
          Import-Module Pester -PassThru
          Invoke-Pester