run-name: 🎉 Your First Binary PS Module! 🎉
on: [
  push,
  pull_request
]
defaults:
  run:
    shell: pwsh
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 🧪 Pester Tests
        id: test
        run: |
          Write-Host -Fore Green "Running Available Tests in $PWD"
          Install-Module -Name Pester -Force -SkipPublisherCheck -WarningAction SilentlyContinue
          Get-Content tests/Example.1.PowerShell.Tests.ps1
          Invoke-Pester tets/Example.1.PowerShell.Tests.ps1